%package -n patterns-sailfish-device-configuration-sparkler
Summary: Jolla Configuration for Nokia 8000 4G
Requires: patterns-sailfish-device-configuration-common-sparkler
Requires: patterns-sailfish-device-adaptation-sparkler

Requires: patterns-sailfish-cellular-apps
Requires: patterns-sailfish-device-tools

Requires: sailfish-content-graphics-z1.0

Requires: jolla-settings-networking-multisim
Requires: jolla-settings-accounts-extensions-3rd-party-all
Requires: patterns-sailfish-consumer-generic

%description -n patterns-sailfish-device-configuration-sparkler
Pattern with packages for Nokia 8000 4G configurations

%files -n patterns-sailfish-device-configuration-sparkler

# vim: ft=spec
