%package -n patterns-sailfish-device-adaptation-sparkler
Summary: Jolla HW Adaptation for Nokia 8000 4G
Requires: device-configuration-sparkler
Requires: device-sparkler-img-boot
Requires: device-sparkler-img-recovery
Requires: kernel-adaptation-msm8909
Requires: mesa-llvmpipe-dri-swrast-driver
Requires: mipi-dbi-configs
Requires: qt5-plugin-platform-eglfs
Requires: qrtr
Requires: rmtfs


%description -n patterns-sailfish-device-adaptation-sparkler
Pattern with packages for Nokia 8000 4G HW adaptation

%files -n patterns-sailfish-device-adaptation-sparkler

# vim: ft=spec
